name: Assemble
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 11
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble app
        run: ./gradlew assemble
